# Generated by Django 5.1.4 on 2024-12-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('recipes', '0002_recipe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
    ]
