# Generated by Django 5.1.4 on 2024-12-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recipes',
        ),
    ]
